apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user-user-example.com-clusterrole-edit
  namespace: cns
  annotations:
    role: view
    user: user@example.com
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeflow-edit
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: user@example.com